version: "3.3"

services:
  api:
    build:
      context: ./backend/SquareNews
    ports:
      - "80:80"
    depends_on:
      - sql

  web:
    build:
      context: ./frontend
    ports:
      - "8080:8080"

  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=ArticleSquare#2023
      - ACCEPT_EULA=Y
    ports:
      - "1450:1433"